config/routes.rb
Rails.application.routes.draw do
  root 'customers#index'

  resources :customers do
    get 'export'
  end

  resources :games do
    collection do
      put 'update_availability' => 'games#update_availability'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
require 'csv'

class Customer < ApplicationRecord
  
  # enum game_name: {
  #   "Tilt Brush" => "Tilt Brush",
  #   "Brookhaven" => "Brookhaven",
  #   "The Blu"    => "The Blu"
  # }

  enum age_range: {
    "5 to 9"   => "5 to 9",
    "10 to 12" => "10 to 12",
    "13 to 15" => "13 to 15",
    "16 to 18" => "18 to 25",
    "25 to 30" => "25 to 30",
    "30 to 40" => "30 to 40",
    "40 plus"  => "40 plus"
  }

  enum race_field: {
    "Hispanic or Latino"     => "Hispanic or Latino",
    "White"                  => "White",
    "Black/African American" => "Black/African American",
    "Asian"                  => "Asian",
    "Native American"        => "Native American",
    "Middle Eastern"         => "Middle Eastern",
    "Pacific Islander"       => "Pacific Islander",
    "Multiracial"            => "Multiracial"
  }

  enum gender_field: {
    "Male"   => "Male",
    "Female" => "Female"
  }

  enum income_field: {
    "Less than $20,000"  => "Less than $20,000",
    "$20,000 to $34,999" => "$20,000 to $34,999",
    "$35,000 to $49,999" => "$35,000 to $49,999",
    "$50,000 to $74,999" => "$50,000 to $74,999",
    "$74,999 to $99,999" => "$74,999 to $99,999",
    "$100,000 plus"      => "$100,000 plus"
  }

  enum group_type: {
    "Individual"             => "Individual",
    "Couple-Date"            => "Couple-Date",
    "Group-Friends"          => "Group-Friends",
    "Group-Family"           => "Group-Family",
    "Group-Immediate Family" => "Group-Immediate Family"
  }
  validates :date, :machine, presence:true
  #validates_associated :game
  validates :age, inclusion: { in: age_ranges.keys, message: "Please Select Age Range"}
  validates :gender, inclusion: { in: gender_fields.keys, message: "Please Select Gender"}
  validates :race, inclusion: { in: race_fields.keys, message: "Please Select Race"}
  validates :income, inclusion: { in: income_fields.keys, message: "Please Select Income Range"}
  validates :group_type, inclusion: { in: group_types.keys, message: "Please Select Group Type" }
  validates :group_size, presence: {message: "Can't be blank"}

  def self.search(paramz)
    start_date = paramz[:start_date].empty? ? ("2000-01-01").to_date : paramz[:start_date].to_date
    end_date = paramz[:end_date].empty? ? ("2100-01-01").to_date : paramz[:end_date].to_date
    age = paramz[:age].empty? ? "%%" : paramz[:age]
    gender = paramz[:gender].empty? ? "%%" : paramz[:gender]
    income = paramz[:income].empty? ? "%%" : paramz[:income]
    race = paramz[:race].empty? ? "%%" : paramz[:race]
    game = paramz[:game].empty? ? "%%" : paramz[:game]
    customers = Customer.where(date: start_date..end_date).where('game LIKE ?', "#{game}").where("gender LIKE ?", "#{gender}").where("age LIKE ?", "#{age}").where("income LIKE ?", "#{income}").where("race LIKE ?", "#{race}")
  end
  
  def self.to_csv
    attributes = %w{date machine game age gender race income group_type group_size}
    CSV.generate(headers: true) do |csv|
      csv << attributes
      
      all.each do |customer|
        csv << attributes.map{ |attr| customer.send(attr) }
      end
    end
  end
end

app/controllers/customers_controller.rb
require 'date'


class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @params = params
    @games = Game.all
    @customers = if !params[:search].present? || (params[:start_date].empty? &&
                      params[:end_date].empty? && params[:age].empty? &&
                      params[:gender].empty? && params[:income].empty? &&
                      params[:race].empty? && params[:game].empty?)
                    Customer.all
                  else
                    Customer.search(params)
                  end
    if params[:format] == 'csv'
      send_data @customers.to_csv, filename: "users_#{DateTime.now.nsec}.csv"
    else
      respond_to do |format|
          format.js
          format.html
      end
    end
  end
  

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
    @games_avail = Game.where(:available => true)
  end

  # GET /customers/1/edit
  def edit
    @machine = @customer.machine
  end

  # POST /customers
  # POST /customers.json
  def create
    byebug
    @customer = Customer.new(customer_params)
    @machine = @customer.machine
    respond_to do |format|
      if @customer.save
        format.js
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:date, :machine, :game, :age, :gender, :race, :income, :group_type, :group_size, :format)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_export-menu.html.erb
<div id="export-menu", remote: true>
  <%= form_tag customers_path, method: :get do  %>
    <%= hidden_field_tag :search, true %>
    <%= hidden_field_tag 'start_date', @params['start_date'] %>
    <%= hidden_field_tag 'end_date', @params['end_date'] %>
    <%= hidden_field_tag :machine, @params[:machine] %>
    <%= hidden_field_tag :game, @params[:game] %>
    <%= hidden_field_tag :gender, @params[:gender] %>
    <%= hidden_field_tag :age, @params[:age] %>
    <%= hidden_field_tag :income, @params[:income] %>
    <%= hidden_field_tag :race, @params[:race] %>
    <%= hidden_field_tag :group_type, @params[:group_type] %>
    <%= button_tag "Export CSV", :value => 'csv', :name => 'format', class: 'blue-btn' %>
    <% end %>
</div>

app/views/customers/_form.html.erb
<%= form_for customer, validate: {inclusion: true}, :html => { :id => machine + "_form" }, remote: true do |f| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :date, value: Time.now %>
  <%= f.hidden_field :machine, value: machine %>

  <div class="form-group">
    <%= f.label :game %>
    <% options = options_from_collection_for_select(@games_avail, :id, :title) %>
    <%= f.select :game, options,
                        prompt: 'Select a Game' %>
  </div>

  <div class="field">
    <%= f.label :age %>
    <%= f.select :age, Customer.age_ranges.keys,
                        prompt: 'Select Age Range' %>
  </div>

  <div class="field">
    <%= f.label :gender %>
    <%= f.select :gender, Customer.gender_fields.keys,
                        prompt: 'Select Gender'%>
  </div>

  <div class="field">
    <%= f.label :race %>
    <%= f.select :race, Customer.race_fields.keys,
                        prompt: 'Select Race'%>
  </div>

  <div class="field">
    <%= f.label :income %>
    <%= f.select :income, Customer.income_fields.keys,
                          prompt: 'Select Income Range'%>
  </div>

  <div class="field">
    <%= f.label :group_type %>
    <%= f.select :group_type, Customer.group_types.keys,
                            prompt: 'Select Group Type'%>
  </div>

  <div class="field">
    <%= f.label :group_size %>
    <%= f.number_field :group_size %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/_form1.html.erb
<%= form_for(customer) do |f| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- <div class="field">
    <%= f.label :date %>
    <%= f.date_select :date %>
  </div> -->

  <!-- <div class="field">
    <%= f.label :machine %>
    <%= f.text_field :machine %>
  </div> -->

  <div class="field">
    <%= f.label :game %>
    <%= f.text_field :game %>
  </div>

  <div class="field">
    <%= f.label :age %>
    <%= f.text_field :age %>
  </div>

  <div class="field">
    <%= f.label :gender %>
    <%= f.text_field :gender %>
  </div>

  <div class="field">
    <%= f.label :race %>
    <%= f.text_field :race %>
  </div>

  <div class="field">
    <%= f.label :income %>
    <%= f.text_field :income %>
  </div>

  <div class="field">
    <%= f.label :group_type %>
    <%= f.text_field :group_type %>
  </div>

  <div class="field">
    <%= f.label :group_size %>
    <%= f.number_field :group_size %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/_table.html.erb
<table class="table" id="customers-table", remote: true>
  <thead>
    <tr>
      <th>Date</th>
      <th>Machine</th>
      <th>Game</th>
      <th>Age</th>
      <th>Gender</th>
      <th>Race</th>
      <th>Income</th>
      <th>Group type</th>
      <th>Group size</th>
      <th style="width:40px;"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.date %></td>
        <td><%= customer.machine %></td>
        <td><%= customer.game %></td>
        <td><%= customer.age %></td>
        <td><%= customer.gender %></td>
        <td><%= customer.race %></td>
        <td><%= customer.income %></td>
        <td><%= customer.group_type %></td>
        <td><%= customer.group_size %></td>
        <td class="hide-link"><div class='hidden-link-container'><%= link_to fa_icon('pencil'), edit_customer_path(customer), class: "edit-delete-icon" %></div></td>
        <td class="hide-link"><div class='hidden-link-container'><%= link_to fa_icon('trash'), customer, method: :delete, data: { confirm: 'Are you sure?' }, class: "edit-delete-icon" %></div></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/customers/create.js.erb
if ('<%= @machine %>' == 'machine_1') {
  $("#machine_1_form").replaceWith("<%= j(render 'form', customer: Customer.new, machine: @machine) %>");
}
else if ('<%= @machine %>' == 'machine_2') {
  $("#machine_2_form").replaceWith("<%= j(render 'form', customer: Customer.new, machine: @machine) %>");
}

app/views/customers/edit.html.erb
<% if user_signed_in? %>
  <h1>Editing Customer</h1>
  
  <div class="columns">
    <div class='forms-holder' align='middle'>
      <%= render 'form', customer: @customer, machine: @customer.machine %>
    </div>
  </div>
<% else %>

<% end %>

app/views/customers/index.html.erb
<div class="row">
  <p id="notice"><%= notice %></p>
</div>
<div class="row">
  <div class="col-sm-10">
    <div class="table-responsiv">
      <h1>Customers</h1>
      <%= render 'table', collection: @customers %>
    </div>
  </div>
  <div class="col-sm-2">
    <div class="panel-group" id="accordion">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class="panel-title">
            <a data-toggle="collapse" data-parent="#accordion" href="#collapse1">Filters</a>
          </h4>
        </div>
        <div id="collapse1" class="panel-collapse collapse">
          <div class="panel-body">
            <%= form_tag customers_path, method: :get, remote: true do %>
        <div>
          <%= date_field_tag 'start_date', '2017-01-01', {class: "form_control"} %>
          <%= date_field_tag 'end_date', nil, {type: "div", class: "form_control"} %>
          <% options = options_from_collection_for_select(@games, :id, :title) %>
          <%= select_tag :game, options, prompt: 'Select a Game', class:"form_control" %>
          <%= select_tag :gender, options_from_collection_for_select(Customer::gender_fields, :first, :last),
              prompt: 'Select Gender', class:"form_control" %>
          <%= select_tag :age, options_from_collection_for_select(Customer::age_ranges, :first, :last),
              prompt: 'Select Age Range', class: "form_control" %>
          <%= select_tag :income, options_from_collection_for_select(Customer::income_fields, :first, :last),
              prompt: 'Select Income Range', class: "form_control" %>
          <%= select_tag :race, options_from_collection_for_select(Customer::race_fields, :first, :last),
              prompt: 'Select Race', class:"form_control" %>
          <%= select_tag :group_type, options_from_collection_for_select(Customer::group_types, :first, :last),
              prompt: 'Select Group Type', class:"form_control" %>
          <%= hidden_field :search, name: "search", value: true%>
          <span class='submit-button'>
            <%= fa_icon 'search' %>
            <!-- :name => nil will make url cleaner -->
            <%= submit_tag "Search", :name => nil, class: 'btn btn-default' %>
          </span>
        </div>
      <% end %>
          </div>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class="panel-title">
            <a data-toggle="collapse" data-parent="#accordion" href="#collapse2">Export</a>
          </h4>
        </div>
        <div id="collapse2" class="panel-collapse collapse">
          <div class="panel-body">
            <%= render 'export-menu', collection: :params %>
          </div>
    </div>
  </div>
</div>

app/views/customers/index.js.erb
$("#customers-table").replaceWith("<%= j(render 'table', collection: @customers) %>");

$("#export-menu").replaceWith("<%= j(render 'export-menu', collection: :params) %>");

app/views/customers/new.html.erb
<% if user_signed_in? %>  
  <h1>New Customer</h1>
  
  <div class="columns">
    <div class='forms-holder'>
      <div class="left">
        <h2>Machine 1</h2>
        <%= render 'form', customer: Customer.new, machine: "machine_1" %>
      </div>
      <div class="right">
        <h2>Machine 2</h2>
        <%= render 'form', customer: Customer.new, machine: "machine_2" %>
      </div>
    </div>
  </div>
<% else %>

<% end %>

app/views/customers/show.html.erb
<% if user_signed_in? %>  
  <p id="notice"><%= notice %></p>
  
  <p>
    <strong>Date:</strong>
    <%= @customer.date %>
  </p>
  
  <p>
    <strong>Machine:</strong>
    <%= @customer.machine %>
  </p>
  
  <p>
    <strong>Game:</strong>
    <%= @customer.game %>
  </p>
  
  <p>
    <strong>Age:</strong>
    <%= @customer.age %>
  </p>
  
  <p>
    <strong>Gender:</strong>
    <%= @customer.gender %>
  </p>
  
  <p>
    <strong>Race:</strong>
    <%= @customer.race %>
  </p>
  
  <p>
    <strong>Income:</strong>
    <%= @customer.income %>
  </p>
  
  <p>
    <strong>Group type:</strong>
    <%= @customer.group_type %>
  </p>
  
  <p>
    <strong>Group size:</strong>
    <%= @customer.group_size %>
  </p>
  
  <%= link_to 'Edit', edit_customer_path(@customer) %> |
  <%= link_to 'Back', customers_path %>
<% else %>

<% end %>