config/routes.rb
Rails.application.routes.draw do
  root 'customers#index'

  resources :customers do
    get 'export'
  end

  resources :games do
    collection do
      put 'update_availability' => 'games#update_availability'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/game.rb
class Game < ApplicationRecord
    
    def add_game_availability(params)
        
    end

    def self.change_game_availability(available, unavailable)
        Game.where(id: available).update_all(available: true) if available.present?
        Game.where(id: unavailable).update_all(available: false) if unavailable.present?
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
    @games_avail = Game.where(:available => true)
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @games = Game.all
  end

  def update_availability
    Game.change_game_availability(params[:checked], params[:unchecked])
    # render :nothing => true
    head :ok 
  end

  # GET /games/new
  def new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:game, :title, :available)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for game, remote: true do |f| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :available %>
    <%= f.check_box :available %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/_table.html.erb
<table class="table" id="games-table", remote: true>
  <thead>
    <tr>
      <th>Game</th>
      <th>Available?</th>
      <th style="width=40px"></th>
    </tr>
  </thead>

  <tbody>
    <% collection.each do |game| %>
      <tr>
        <!--<td><%= hidden_field_tag "game_id" , value = game.id %></td>-->
        <td data-game-id=<%= game.id %> ><%= game.title %></td>
        <td><%= check_box_tag "#{game.id}", value= nil, checked = game.available, class: 'available-checkbox', disabled: true %></td>
        <td class="hide-link"><%= link_to fa_icon('pencil'), edit_game_path(game), class: "edit-delete-icon" %></td>
        <td class="hide-link"><%= link_to fa_icon('trash'), game, method: :delete, data: { confirm: 'Are you sure?' }, class: "edit-delete-icon" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/games/create.js.erb
$("#new_game_form").replaceWith("<%= j(render 'form', game: @game) %>");

$("#games-table").replaceWith("<%= j(render 'table', collection: @games) %>");

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<div class="row">
  <p id="notice"><%= notice %></p>
</div>
<div class="row">
  <div class="col-sm-4"></div>
  <div class="col-sm-4">
    <div class="table-responsiv">
      <h1>Games</h1>
      <%= render 'table', collection: @games %>
    </div>
  </div>
  <div class="col-sm-2">
    <div class="panel-group" id="accordion">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class="panel-title">
            <a data-toggle="collapse" data-parent="#accordion" href="#collapse1">Update</a>
          </h4>
        </div>
        <div id="collapse1" class="panel-collapse collapse">
          <div class="panel-body">
            <script>
            </script>
            <button id="edit-available" type="button" class="btn btn-default">Edit</button>
            <button data-url='<%= update_availability_games_url %>'  id="update" type="button" class="btn btn-default" style='display:none'>Update</button>
            <button id="cancel" type="button" class="btn btn-default" style='display:none'>Cancel</button>
          </div>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class="panel-title">
            <a data-toggle="collapse" data-parent="#accordion" href="#collapse2">Add A Game</a>
          </h4>
        </div>
        <div id="collapse2" class="panel-collapse collapse">
          <div class="panel-body">
            <%= render 'form', game: Game.new %>
          </div>
    </div>
  </div>
</div>


<%= link_to 'New Game', new_game_path %>

app/views/games/index.js.erb
$("#games-table").replaceWith("<%= j(render 'table', collection: @games) %>");

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: Game.new %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @game.title %>
</p>

<p>
  <strong>Available:</strong>
  <%= @game.available %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/games/update.js.erb
$("#games-table").replaceWith("<%= j(render 'table', collection: @games) %>");