config/routes.rb
Rails.application.routes.draw do
  root 'customers#index'

  resources :customers do
    get 'export'
  end

  resources :games do
    collection do
      put 'update_availability' => 'games#update_availability'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<%= javascript_include_tag 'application.js' %>
<html>
  <head>
    <title>Survey</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!-- --><%= stylesheet_link_tag "application", media: "all",
      "data-turbolinks-track" => 'reload' %>
    
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %><!-- -->
  </head>
  <body>
    <nav class="navbar  navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">EdenVR</a>
        </div>
        <ul class="nav navbar-nav">
          <li><%= link_to 'Customers', customers_path %></li>
          <li><%= link_to '+Add Customer', new_customer_path,
            style: 'border-left: 1px solid;' %></li>
          <li><%= link_to 'Games', games_path,
            style: 'border-left: 1px solid;' %></li>
        </ul>
      </div>
    </nav>
  
      
    <div id="body" class="container-fluid bg-1 text-center">
      <div class='<%= controller.controller_name %>'>
        <%= yield %>
      </div>
    </div>
  </body>
</html>